"""Parity tests for the fused Triton dispersion kernel, across every P it covers.

The Triton path re-derives the Cox-Reid term in registers rather than reusing
`_deseq2_core`'s batched tensor ops, so its P x P linear algebra (logdet(b) and
trace(b^-1 db), b = X'WX) is separate straight-line code per P: hand-written for
P in {2, 4}, generated by `_cr_source` for P in {3, 5, 6}. That makes P-coverage
the natural axis to test on — a mistake in one P's algebra is invisible in every
other P.

These tests are skipped without CUDA + Triton. Tolerances are calibrated from
measured drift; the Triton path is deliberately not bit-identical to eager
(different reduction order), so agreement is checked at ~1e-12 on the objective
and via a p95 on the fitted dispersions.
"""

from __future__ import annotations

import pytest
import torch

from gpu_deseq import _deseq2_core as core
from gpu_deseq import _triton_fit as tri

pytestmark = pytest.mark.skipif(
    not (torch.cuda.is_available() and tri.TRITON_AVAILABLE),
    reason="fused Triton dispersion path requires CUDA + Triton",
)

COVERED_P = (2, 3, 4, 5, 6)
G = 2000


def _design(n_samples: int, n_vars: int) -> torch.Tensor:
    """Intercept plus a balanced (n_vars-1)-level factor."""
    x = torch.zeros(n_samples, n_vars, dtype=torch.float64, device="cuda")
    x[:, 0] = 1.0
    group = torch.arange(n_samples, device="cuda") % n_vars
    for j in range(1, n_vars):
        x[:, j] = (group == j).double()
    assert int(torch.linalg.matrix_rank(x).item()) == n_vars
    return x


def _nb_fixture(n_samples: int, n_vars: int, seed: int = 0):
    """Negative-binomial counts via the gamma-Poisson mixture DESeq2 assumes."""
    torch.manual_seed(seed)
    design = _design(n_samples, n_vars)
    base = torch.exp(torch.rand(G, 1, dtype=torch.float64, device="cuda") * 6 + 2)
    mu = (base * torch.exp(torch.randn(G, n_samples, dtype=torch.float64,
                                       device="cuda") * 0.15)).clamp_min(0.1)
    disp = torch.exp(torch.randn(G, 1, dtype=torch.float64, device="cuda") * 0.6 - 1.5)
    shape = 1.0 / disp
    gamma = torch._standard_gamma(shape.expand_as(mu)) / shape
    counts = torch.poisson(mu * gamma).double()
    size_factors = torch.ones(n_samples, dtype=torch.float64, device="cuda")
    alpha_init = core.fit_initial_dispersions(counts, size_factors, design)
    return counts, mu, design, alpha_init


def test_supports_p_matches_covered_range() -> None:
    for p in COVERED_P:
        assert tri.supports_p(p), f"P={p} should be covered"
    # P=1 would read past the end of a design row and P=7 would silently drop
    # trailing columns, so both must stay gated off rather than "mostly work".
    assert not tri.supports_p(1)
    assert not tri.supports_p(max(COVERED_P) + 1)


@pytest.mark.parametrize("n_vars", [1, max(COVERED_P) + 1])
def test_launch_rejects_uncovered_p(n_vars: int) -> None:
    """An uncovered P must raise, not quietly fit the wrong model.

    The kernel reads exactly `_MAX_P` design columns, so without this guard a
    narrower design reads past the end of a row and a wider one silently drops
    its trailing columns — both produce plausible numbers for the wrong model.
    """
    counts, mu, _, alpha_init = _nb_fixture(12, 2)
    design = torch.zeros(12, n_vars, dtype=torch.float64, device="cuda")
    design[:, 0] = 1.0
    for j in range(1, n_vars):
        design[:, j] = (torch.arange(12, device="cuda") % n_vars == j).double()
    with pytest.raises(ValueError, match="Triton dispersion path covers"):
        tri._launch(counts, mu, design, alpha_init, None, None, 100)


@pytest.mark.parametrize("n_vars", COVERED_P)
@pytest.mark.parametrize("n_samples", [8, 12, 24])
def test_cox_reid_objective_matches_eager(n_vars: int, n_samples: int) -> None:
    """The register-resident Cox-Reid term must match the batched tensor version.

    This is the tightest available check: it pins lp/dlp at a fixed alpha, so it
    isolates the per-P linear algebra from any optimizer path divergence.
    """
    if n_samples <= n_vars:
        pytest.skip("design must have residual degrees of freedom")
    counts, mu, design, _ = _nb_fixture(n_samples, n_vars)
    log_alpha = torch.log(torch.rand(G, dtype=torch.float64, device="cuda") * 0.5 + 0.01)

    lp_ref, dlp_ref = core._lp_and_dlp(counts, mu, design, log_alpha)
    lp = torch.empty(G, dtype=torch.float64, device="cuda")
    dlp = torch.empty(G, dtype=torch.float64, device="cuda")
    _eval_objective(counts, mu, design, log_alpha, lp, dlp)

    assert torch.isfinite(lp).all() and torch.isfinite(dlp).all()
    lp_rel = ((lp - lp_ref).abs() / lp_ref.abs().clamp_min(1e-300)).max()
    # dlp crosses zero at the optimum, so normalize by the gradient's own scale
    # rather than per-element: a near-zero element makes plain relative error
    # meaningless without saying anything about the algebra.
    dlp_scale = dlp_ref.abs().median()
    dlp_rel = ((dlp - dlp_ref).abs() / dlp_ref.abs().clamp_min(dlp_scale)).max()
    assert float(lp_rel) < 1e-13, f"logposterior drift {float(lp_rel):.2e}"
    assert float(dlp_rel) < 1e-12, f"gradient drift {float(dlp_rel):.2e}"


@pytest.mark.parametrize("n_vars", COVERED_P)
@pytest.mark.parametrize("n_samples", [8, 12, 24])
def test_fitted_dispersions_match_eager(n_vars: int, n_samples: int) -> None:
    if n_samples <= n_vars:
        pytest.skip("design must have residual degrees of freedom")
    counts, mu, design, alpha_init = _nb_fixture(n_samples, n_vars)

    mle_ref = core.fit_alpha_mle(counts, mu, design, alpha_init=alpha_init)
    mle = tri.fit_alpha_mle_triton(counts, mu, design, alpha_init)

    trend = torch.full((G,), 0.15, dtype=torch.float64, device="cuda")
    map_ref = core.fit_alpha_map(counts, mu, design, alpha_hat=trend,
                                 prior_disp_var=0.25, alpha_init=alpha_init)
    map_got = tri.fit_alpha_map_triton(counts, mu, design, trend, 0.25, alpha_init)

    for name, got, ref, tol in (("gene-est", mle, mle_ref, 1e-12),
                                ("MAP", map_got, map_ref, 1e-12)):
        assert torch.isfinite(got).all(), f"{name} produced non-finite dispersions"
        rel = (got - ref).abs() / ref.abs().clamp_min(1e-300)
        p95 = float(rel.quantile(0.95))
        assert p95 < tol, f"{name} p95 relative drift {p95:.2e} (P={n_vars}, n={n_samples})"


def _eval_objective(counts, mu, design, log_alpha, lp_out, dlp_out) -> None:
    """Run one _lpdlp evaluation per gene at a fixed log-alpha."""
    import triton

    src = """
@triton.jit
def _test_eval_lpdlp(counts_ptr, mu_ptr, x_ptr, a_ptr, lp_ptr, dlp_ptr,
                     S: tl.constexpr, BLOCK_S: tl.constexpr, P: tl.constexpr):
    g = tl.program_id(0)
    s = tl.arange(0, BLOCK_S)
    mask = s < S
    counts = tl.load(counts_ptr + g * S + s, mask=mask, other=0.0)
    mu = tl.load(mu_ptr + g * S + s, mask=mask, other=1.0)
    x0 = tl.load(x_ptr + s * P + 0, mask=mask, other=0.0)
    x1 = tl.load(x_ptr + s * P + 1, mask=mask, other=0.0)
    x2 = tl.load(x_ptr + s * P + 2, mask=mask, other=0.0) if P > 2 else s * 0.0
    x3 = tl.load(x_ptr + s * P + 3, mask=mask, other=0.0) if P > 3 else s * 0.0
    x4 = tl.load(x_ptr + s * P + 4, mask=mask, other=0.0) if P > 4 else s * 0.0
    x5 = tl.load(x_ptr + s * P + 5, mask=mask, other=0.0) if P > 5 else s * 0.0
    a = tl.load(a_ptr + g)
    lp, dlp = _lpdlp(counts, mu, x0, x1, x2, x3, x4, x5, mask, a, 0.0, 1.0, False, P)
    tl.store(lp_ptr + g, lp)
    tl.store(dlp_ptr + g, dlp)
"""
    if not hasattr(tri, "_test_eval_lpdlp"):
        tri._exec_generated(src, "test objective probe")
    n_genes, n_samples = counts.shape
    tri._test_eval_lpdlp[(n_genes,)](
        counts.contiguous(), mu.contiguous(), design.contiguous(),
        log_alpha.contiguous(), lp_out, dlp_out,
        S=n_samples, BLOCK_S=triton.next_power_of_2(n_samples), P=design.shape[1])
