"""Parity tests against real R Bioconductor DESeq2 output.

Fixtures are generated by scripts/generate_r_fixtures.R on the same synthetic
recipe as scripts/measure_drift.py. Each fixture directory holds counts.csv,
coldata.csv, and results.csv (R's DESeq() with independentFiltering=FALSE,
cooksCutoff=FALSE, no LFC shrinkage).

Tolerances below reflect actual measured drift — any increase should be
investigated, not accepted.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from gpu_deseq import (
    DESeqDataset,
    fit_dispersions,
    fit_size_factors,
    lfc_shrink,
    results,
    wald_test,
)


FIXTURE_ROOT = Path(__file__).parent.parent / "fixtures" / "r_deseq2"


def _load_fixture(label: str):
    path = FIXTURE_ROOT / label
    if not (path / "results.csv").exists():
        pytest.skip(f"R fixture missing: {path}. Run scripts/generate_r_fixtures.R first.")
    counts = pd.read_csv(path / "counts.csv", index_col=0)
    coldata = pd.read_csv(path / "coldata.csv", index_col=0)
    ref = pd.read_csv(path / "results.csv")
    ref = ref.set_index("gene")
    return counts.to_numpy(dtype=np.float64), coldata, ref, list(counts.index)


def _run_gpu(counts: np.ndarray, coldata: pd.DataFrame, gene_ids):
    dds = DESeqDataset(counts, coldata, design="~ condition",
                       gene_ids=gene_ids, backend="torch")
    fit_size_factors(dds)
    fit_dispersions(dds)
    return results(wald_test(dds, contrast="condition[T.treated]"),
                   cooks_filter=False, independent_filter=False), dds


# Tolerances below were calibrated by running against R DESeq2 1.30.1 output.
# Measured p95 relative errors (see fixtures/r_deseq2/plots/summary.csv):
#   large_60x2000 → disp 0.22%, lfc 0.01%, lfcSE 0.10%
#   medium_30x500 → disp 0.33%, lfc 1.36%, lfcSE 0.16%
#   small_12x200  → disp 0.69%, lfc 6.10%, lfcSE 0.33%
# The LFC p95-relative on small/medium is dominated by genes whose true LFC is
# near 0 (tiny absolute diffs blown up by division). Correlations and p95-abs
# diffs are essentially perfect; see scripts/compare_vs_r.py for full stats.
@pytest.mark.parametrize(
    "label,disp_p95,lfc_p95_abs,se_p95,pval_corr_min",
    [
        ("large_60x2000", 0.005, 5e-5,  0.005, 0.99999),
        ("medium_30x500", 0.006, 2e-3,  0.005, 0.99999),
        ("small_12x200",  0.015, 1e-2,  0.010, 0.999),
    ],
)
def test_against_r_deseq2(label: str, disp_p95: float, lfc_p95_abs: float,
                          se_p95: float, pval_corr_min: float) -> None:
    counts, coldata, ref, gene_ids = _load_fixture(label)
    ours, dds = _run_gpu(counts, coldata, gene_ids)

    merged = ours.join(ref, rsuffix="_r")
    finite = np.isfinite(merged[["log2FoldChange", "log2FoldChange_r",
                                  "lfcSE", "lfcSE_r"]]).all(axis=1)
    merged = merged[finite]

    # Dispersions: per-gene α should match to disp_p95 relative at p95.
    our_disp = dds.dispersions.cpu().numpy()
    mask = np.isfinite(our_disp) & np.isfinite(ref["dispersion"].to_numpy())
    rel_disp = np.abs(our_disp[mask] - ref["dispersion"].to_numpy()[mask]) / \
        (np.abs(ref["dispersion"].to_numpy()[mask]) + 1e-12)
    assert np.percentile(rel_disp, 95) < disp_p95, (
        f"{label}: p95 dispersion rel err {np.percentile(rel_disp, 95):.4g} >= {disp_p95}")

    # LFC: absolute error at p95 (avoids the near-zero-LFC relative-error blowup).
    lfc_err = np.abs(merged["log2FoldChange"].to_numpy() - merged["log2FoldChange_r"].to_numpy())
    assert np.percentile(lfc_err, 95) < lfc_p95_abs, (
        f"{label}: p95 |LFC err| {np.percentile(lfc_err, 95):.4g} >= {lfc_p95_abs}")

    # lfcSE: relative error at p95.
    se_rel = np.abs(merged["lfcSE"].to_numpy() - merged["lfcSE_r"].to_numpy()) / \
        (np.abs(merged["lfcSE_r"].to_numpy()) + 1e-9)
    assert np.percentile(se_rel, 95) < se_p95, (
        f"{label}: p95 lfcSE rel err {np.percentile(se_rel, 95):.4g} >= {se_p95}")

    # p-value Pearson correlation — end-to-end signal agreement.
    corr = np.corrcoef(merged["pvalue"], merged["pvalue_r"])[0, 1]
    assert corr > pval_corr_min, f"{label}: pvalue Pearson {corr:.6f} <= {pval_corr_min}"

    # Signs must match on meaningful effects.
    meaningful = np.abs(merged["log2FoldChange_r"]) > 0.1
    sign_match = np.sign(merged["log2FoldChange"][meaningful]) == \
        np.sign(merged["log2FoldChange_r"][meaningful])
    assert sign_match.mean() > 0.99, f"{label}: sign agreement {sign_match.mean():.3f}"

    # Significance calls at alpha=0.05 on raw p should have high Jaccard.
    our_sig = merged["pvalue"] < 0.05
    ref_sig = merged["pvalue_r"] < 0.05
    jaccard = (our_sig & ref_sig).sum() / max((our_sig | ref_sig).sum(), 1)
    assert jaccard > 0.95, f"{label}: significance Jaccard {jaccard:.3f}"


# Shrunk-LFC parity tests against R apeglm (lfcShrink(type="apeglm")).
# Tolerances come from scripts/compare_vs_r.py and consistency plots; any
# regression should be investigated, not absorbed.
@pytest.mark.parametrize(
    "label,lfc_p95_abs,se_p95_rel,corr_min",
    [
        ("large_60x2000", 0.002, 0.003, 0.9999),
        ("medium_30x500", 0.003, 0.004, 0.9999),
        # Small fixture: EB prior estimation is noisy with n=12, still corr>0.999.
        ("small_12x200",  0.1,   0.03,  0.999),
    ],
)
def test_apeglm_shrinkage_against_r(label: str, lfc_p95_abs: float,
                                    se_p95_rel: float, corr_min: float) -> None:
    counts, coldata, ref, gene_ids = _load_fixture(label)
    if "log2FoldChange_apeglm" not in ref.columns or ref["log2FoldChange_apeglm"].isna().all():
        pytest.skip(f"{label}: no R apeglm fixture")

    dds = DESeqDataset(counts, coldata, design="~ condition",
                       gene_ids=gene_ids, backend="torch")
    fit_size_factors(dds)
    fit_dispersions(dds)
    wald = wald_test(dds, contrast="condition[T.treated]")
    shrunk = lfc_shrink(wald, coeff="condition[T.treated]")
    ours = results(shrunk, cooks_filter=False, independent_filter=False)

    merged = ours.join(ref[["log2FoldChange_apeglm", "lfcSE_apeglm"]])
    finite = np.isfinite(merged[["log2FoldChange", "log2FoldChange_apeglm",
                                  "lfcSE", "lfcSE_apeglm"]]).all(axis=1)
    m = merged[finite]

    lfc_abs = np.abs(m["log2FoldChange"].to_numpy() - m["log2FoldChange_apeglm"].to_numpy())
    assert np.percentile(lfc_abs, 95) < lfc_p95_abs, (
        f"{label}: shrunk LFC p95 |abs| {np.percentile(lfc_abs, 95):.4g} >= {lfc_p95_abs}")

    se_rel = np.abs(m["lfcSE"].to_numpy() - m["lfcSE_apeglm"].to_numpy()) / \
        (np.abs(m["lfcSE_apeglm"].to_numpy()) + 1e-9)
    assert np.percentile(se_rel, 95) < se_p95_rel, (
        f"{label}: shrunk SE p95 rel {np.percentile(se_rel, 95):.4g} >= {se_p95_rel}")

    lfc_corr = np.corrcoef(m["log2FoldChange"], m["log2FoldChange_apeglm"])[0, 1]
    se_corr = np.corrcoef(m["lfcSE"], m["lfcSE_apeglm"])[0, 1]
    assert lfc_corr > corr_min, f"{label}: shrunk LFC corr {lfc_corr:.6f} <= {corr_min}"
    assert se_corr  > corr_min, f"{label}: shrunk SE  corr {se_corr:.6f} <= {corr_min}"
