"""Realistic-scale end-to-end parity against the current R Bioconductor DESeq2.

The 6-sample fixtures in test_api.py fall into degenerate regimes (the
parametric trend fit punts to the mean fallback, and the dispersion prior is
poorly estimated with residual dof < 3). A meaningful end-to-end comparison
needs larger n to exercise the primary code paths.

This module reuses the larger single-factor R fixtures generated by
scripts/generate_r_fixtures.R (`medium_30x500`, seed 0; `large_60x2000`,
seed 1). Each fixture stores the exact count matrix R ran on plus R DESeq2's
own results.csv / dispersions.csv, so we compare gpu-deseq against R itself
on identical data — not against any third-party re-implementation.

Where test_r_step_parity.py pins each kernel independently, this test checks
that the *full* results() path (dispersions -> beta -> Wald SE -> stat ->
pvalue) lines up end-to-end, so compensating per-step errors can't hide.

Tolerances are derived from measured drift on these fixtures, not aspirational.
gpu-deseq targets R bit-exactly, so the end-to-end p95 relative errors are
~1e-6 (LFC/stat) and ~1e-7 (dispersion/SE); the bounds below sit comfortably
above the measured values. Tightening them is fine; loosening one means
something regressed.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from gpu_deseq import DESeqDataset, fit_dispersions, fit_size_factors, results, wald_test

FIXTURE_ROOT = Path(__file__).parent.parent / "fixtures" / "r_deseq2"


def _load_fixture(label: str):
    path = FIXTURE_ROOT / label
    if not (path / "results.csv").exists():
        pytest.skip(f"R fixtures missing for {label}; rerun scripts/generate_r_fixtures.R")
    counts = pd.read_csv(path / "counts.csv", index_col=0)
    coldata = pd.read_csv(path / "coldata.csv", index_col=0)
    r_results = pd.read_csv(path / "results.csv").set_index("gene")
    r_disp = pd.read_csv(path / "dispersions.csv").set_index("gene")["dispersion"]
    return counts, coldata, r_results, r_disp


def _run_gpu_deseq(counts: pd.DataFrame, coldata: pd.DataFrame):
    dds = DESeqDataset(
        counts.to_numpy(dtype=np.float64),
        coldata,
        design="~ condition",
        gene_ids=list(counts.index),
        sample_ids=list(counts.columns),
        backend="torch",
    )
    fit_size_factors(dds)
    fit_dispersions(dds)
    res = results(
        wald_test(dds, contrast="condition[T.treated]"),
        cooks_filter=False,
        independent_filter=False,
    )
    return res, dds


def _p95_rel(a: np.ndarray, b: np.ndarray) -> float:
    a = np.asarray(a, dtype=np.float64)
    b = np.asarray(b, dtype=np.float64)
    mask = np.isfinite(a) & np.isfinite(b)
    rel = np.abs(a[mask] - b[mask]) / (np.abs(b[mask]) + 1e-9)
    return float(np.percentile(rel, 95))


@pytest.mark.parametrize(
    "label,disp_p95_rel,lfc_p95_rel,se_p95_rel",
    [
        ("medium_30x500", 0.006, 0.02, 0.005),
        ("large_60x2000", 0.005, 2e-4, 0.005),
    ],
)
def test_matches_r_deseq2_on_realistic_data(
    label: str, disp_p95_rel: float, lfc_p95_rel: float, se_p95_rel: float,
) -> None:
    counts, coldata, ref, ref_disp = _load_fixture(label)
    ours, our_dds = _run_gpu_deseq(counts, coldata)

    # Dispersions: p95 relative error on per-gene final alpha vs R.
    our_disp = our_dds.dispersions.cpu().numpy()
    p95 = _p95_rel(our_disp, ref_disp.to_numpy())
    assert p95 < disp_p95_rel, f"dispersion p95 rel err {p95:.4g} >= {disp_p95_rel}"

    # LFC / SE: p95 relative error on finite rows.
    merged = ours.join(ref[["log2FoldChange", "lfcSE", "stat", "pvalue"]], rsuffix="_ref")
    finite = np.isfinite(
        merged[["log2FoldChange", "log2FoldChange_ref", "lfcSE", "lfcSE_ref"]]
    ).all(axis=1)
    merged = merged[finite]
    for col, tol in [("log2FoldChange", lfc_p95_rel), ("lfcSE", se_p95_rel)]:
        p95 = _p95_rel(merged[col].to_numpy(), merged[f"{col}_ref"].to_numpy())
        assert p95 < tol, f"{col} p95 rel err {p95:.4g} >= {tol}"

    # pvalue correlation must be essentially 1.
    assert np.corrcoef(merged["pvalue"], merged["pvalue_ref"])[0, 1] > 0.9999

    # Signs agree on meaningful effects.
    meaningful = np.abs(merged["log2FoldChange_ref"]) > 0.1
    sign_match = np.sign(merged["log2FoldChange"][meaningful]) == \
        np.sign(merged["log2FoldChange_ref"][meaningful])
    assert sign_match.mean() > 0.995
