"""Render a cross-host comparison of the R DESeq2 baseline.

The R column in bench/results/TABLES.md is the current reference measurement on
one machine. This script adds historical R columns from
run_r_scaling.sh runs on other hosts, WITHOUT modifying TABLES.md or
timings.json -- those stay the record of the current reference session.

Inputs
  bench/results/timings.json                 the reference R column (host A)
  <out>/r_scaling.jsonl (one or more)         new hosts, from run_r_scaling.sh

Output
  bench/results/R_HOSTS.md

Run:
  python bench/render_r_hosts.py \
      --new bench/results/r_epyc9b14/r_scaling.jsonl \
      [--label "EPYC 9B14"] [--out bench/results/R_HOSTS.md]

Every column carries its own host + DESeq2/apeglm version, because a newer
DESeq2 on a newer CPU confounds two variables at once; the ratio column is
labelled as a combined hardware+software effect rather than a speedup.
"""
from __future__ import annotations

import argparse
import json
import pathlib

SUBSTEPS = ["normalization", "dispersion", "glm_fit", "significance", "lfc_shrink", "total"]

REF_LABEL = "A100 host"
REF_NOTE = ("R 4.6.0, DESeq2 1.52.0, apeglm 1.34.0, single thread, as committed in "
            "`bench/results/timings.json` (the source of the R column in `TABLES.md`)")


def load_jsonl(path: pathlib.Path):
    """Return (meta, {case: serial_fine_row}, [sweep_rows])."""
    meta, fine, sweep = {}, {}, []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        rec = json.loads(line)
        kind = rec.get("kind")
        if kind == "meta":
            meta = rec
        elif kind == "serial_fine":
            fine[rec["case"]] = rec
        elif kind == "sweep":
            sweep.append(rec)
    return meta, fine, sweep


def fmt(v):
    return "--" if v is None else f"{round(v):,d}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--new", action="append", required=True,
                    help="r_scaling.jsonl from a new host (repeatable)")
    ap.add_argument("--label", action="append", default=None,
                    help="column label per --new (default: host string from the file)")
    ap.add_argument("--out", default="bench/results/R_HOSTS.md")
    ap.add_argument("--blas-probe", action="append", default=None,
                    help="bench/blas_sensitivity.R output to inline as a "
                         "provenance check (repeatable, paired with --new)")
    ap.add_argument("--json-out", default=None,
                    help="also write the derived comparison as JSON, for tooling "
                         "that needs the numbers without parsing markdown")
    args = ap.parse_args()

    ref = json.load(open("bench/results/timings.json"))["r"]

    hosts = []
    for i, p in enumerate(args.new):
        meta, fine, sweep = load_jsonl(pathlib.Path(p))
        label = (args.label[i] if args.label and i < len(args.label)
                 else meta.get("host", f"host{i+1}"))
        hosts.append({"label": label, "meta": meta, "fine": fine,
                      "sweep": sweep, "path": p})

    cases = sorted(set(ref) | {c for h in hosts for c in h["fine"]})

    L = ["# R DESeq2 baseline across hosts", "",
         "Generated by `bench/render_r_hosts.py`. **Timing only** -- no parity checks,",
         "and no existing result file is modified. Each R column is a separate",
         "measurement of the same five-substep serial call sequence",
         "(`bench/run_r.R` / Track A of `bench/run_r_scaling.sh`) on the same six",
         "datasets.", "",
         "## Columns", "",
         f"- **{REF_LABEL}** -- {REF_NOTE}."]
    for h in hosts:
        m = h["meta"]
        L.append(f"- **{h['label']}** -- R {m.get('r','?')}, DESeq2 {m.get('deseq2','?')}, "
                 f"apeglm {m.get('apeglm','?')}, BLAS `{m.get('blas','?')}`, "
                 f"single thread. Host: `{m.get('host','?')}`. Measured {m.get('utc','?')}.")
    L += ["",
          "> **These columns are not a controlled comparison.** Hardware, R version,",
          "> DESeq2 version and BLAS all differ between them, so a ratio mixes a",
          "> hardware effect with several software ones. Read each column as \"what R",
          "> costs on that machine as configured\", which is what a speedup claim",
          "> against that machine needs -- not as \"how much faster machine B is\".",
          ""]

    # ---- Table: per-substep, all hosts ----
    L += ["## Per-substep serial wall time (median ms)", "",
          "| dataset | substep | " + " | ".join([REF_LABEL] + [h["label"] for h in hosts])
          + " | " + " | ".join(f"ratio {h['label']} / {REF_LABEL}" for h in hosts) + " |",
          "|---|---|" + "--:|" * (len(hosts) + 1) + "--:|" * len(hosts)]
    for c in cases:
        for step in SUBSTEPS:
            rv = ref.get(c, {}).get(step)
            cells = [fmt(rv)]
            ratios = []
            for h in hosts:
                nv = h["fine"].get(c, {}).get(step)
                cells.append(fmt(nv))
                ratios.append(f"{rv/nv:.2f}x" if (rv and nv) else "--")
            bold = "**" if step == "total" else ""
            L.append(f"| {c} | {bold}{step}{bold} | " + " | ".join(cells) + " | "
                     + " | ".join(ratios) + " |")

    # ---- Table: totals + reps ----
    L += ["", "## Totals only (median ms)", "",
          "| dataset | n | genes | P | " + " | ".join([REF_LABEL] + [h["label"] for h in hosts]) + " |",
          "|---|--:|--:|--:|" + "--:|" * (len(hosts) + 1)]
    for c in cases:
        n = genes = P = None
        for h in hosts:
            row = h["fine"].get(c)
            if row:
                n, genes, P = row.get("n"), row.get("genes"), row.get("P")
                break
        cells = [fmt(ref.get(c, {}).get("total"))]
        cells += [fmt(h["fine"].get(c, {}).get("total")) for h in hosts]
        L.append(f"| {c} | {n or '--'} | {genes or '--'} | {P or '--'} | " + " | ".join(cells) + " |")

    # ---- Per-host multi-core best, if swept ----
    for h in hosts:
        if not h["sweep"]:
            continue
        ws = sorted({r["workers"] for r in h["sweep"] if not r.get("failed")})
        if not ws:
            continue
        L += ["", f"## {h['label']} -- multi-core sweep, total pipeline (median ms)", "",
              "`DESeq(minReplicatesForReplace=Inf)` + `results()` + `lfcShrink(apeglm)`,",
              "identical call path at every worker count, so `w=1` is the correct serial",
              "baseline for the parallel speedup (not the per-substep column above,",
              "whose call path differs).", "",
              "| dataset | " + " | ".join(f"w={w}" for w in ws) + " | best | speedup w1->best |",
              "|---|" + "--:|" * (len(ws) + 2)]
        by_case = {}
        for r in h["sweep"]:
            if not r.get("failed"):
                by_case.setdefault(r["case"], {})[r["workers"]] = r["total"]
        for c in sorted(by_case):
            row = by_case[c]
            cells = [fmt(row.get(w)) for w in ws]
            base, best = row.get(1), min(row.values())
            bw = min(row, key=lambda w: row[w])
            L.append(f"| {c} | " + " | ".join(cells) + f" | w={bw} | "
                     + (f"{base/best:.2f}x" if base else "--") + " |")

    # ---- What a different CPU baseline does to the reported speedup ----------
    # The point of adding an R column is to see how much of the headline speedup
    # is "GPU is fast" and how much is "the CPU baseline was slow". cuDESeq2
    # cannot be re-timed on a GPU-less host, so this recombines the EXISTING GPU
    # timings with each R column and labels the result as a recomputation.
    cu = json.load(open("bench/results/timings.json")).get("cu", {})
    if cu and hosts:
        L += ["", "## Effect on the reported speedup (recomputed, not measured)", "",
              "The GPU columns below are retained A100 timings from",
              "`bench/results/timings.json`; only the R denominator changes. Nothing",
              "here is a new GPU measurement -- this host has no GPU -- so these are",
              "arithmetic on existing numbers, shown because swapping the CPU baseline",
              "is exactly what a reviewer would ask about.", "",
              "`best cuDESeq2` = fastest of eager/graph/triton per dataset.", "",
              "| dataset | best cuDESeq2 (A100, ms) | vs A100-host R (published) | "
              + " | ".join(f"vs {h['label']} R serial" for h in hosts) + " | "
              + " | ".join(f"vs {h['label']} R best multi-core" for h in hosts) + " |",
              "|---|--:|--:|" + "--:|" * (2 * len(hosts))]
        for c in cases:
            crow = cu.get(c)
            if not crow or crow.get("_status") == "superseded_for_standard_pipeline":
                continue
            gpu = min(crow[m]["total"] for m in ("eager", "graph", "triton") if m in crow)
            old_r = ref.get(c, {}).get("total")
            cells = [f"{round(gpu):,d}", f"{old_r/gpu:.1f}x" if old_r else "--"]
            for h in hosts:
                nv = h["fine"].get(c, {}).get("total")
                cells.append(f"{nv/gpu:.1f}x" if nv else "--")
            for h in hosts:
                tots = [r["total"] for r in h["sweep"]
                        if r.get("case") == c and not r.get("failed")]
                cells.append(f"{min(tots)/gpu:.1f}x" if tots else "--")
            L.append(f"| {c} | " + " | ".join(cells) + " |")
        L += ["",
              "The spread between the last columns and the published one is the",
              "share of the headline that came from the baseline machine and its",
              "DESeq2 version rather than from the GPU port. Quote whichever",
              "baseline a claim is actually about, and say which host it ran on.", ""]

    # ---- Provenance checks: which of the confounds were actually measured ----
    if args.blas_probe:
        L += ["", "## Provenance check -- does the BLAS difference matter?", "",
              "The caveat above lists BLAS as one of the confounded variables.",
              "That one is testable, so it was tested rather than assumed:",
              "`bench/blas_sensitivity.R` re-times the three expensive substeps",
              "under each BLAS on the same host, single-threaded, selecting the",
              "library with `LD_PRELOAD`.", ""]
        for p in args.blas_probe:
            path = pathlib.Path(p)
            if not path.exists():
                continue
            L += ["```", path.read_text().rstrip(), "```", ""]
        L += ["**Reading it:** the two BLAS runs differ by less than the "
              "run-to-run spread of repeated runs of the *same* configuration, "
              "and not consistently in one direction. DESeq2's per-gene IRLS is "
              "C++ scalar work that does not dispatch through BLAS, matching "
              "`benchmarks/RESULTS.md`'s finding that serial DESeq2 time is "
              "unchanged at 12 vs 1 BLAS threads. So BLAS is *not* a live "
              "confound for these columns; R version and CPU remain.", ""]

    L += ["", "## Sources", ""]
    L.append(f"- {REF_LABEL}: `bench/results/timings.json` (unmodified)")
    for h in hosts:
        L.append(f"- {h['label']}: `{h['path']}`")
    L.append("")

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L))
    print(f"wrote {out}")

    if args.json_out:
        # Derived from the same inputs as the markdown above, so the two cannot
        # disagree. Every speedup here has an explicit denominator name -- the
        # whole point of the second host is that "vs R" is ambiguous.
        payload = {
            "generated_by": "bench/render_r_hosts.py",
            "gpu_timings_are_not_from_these_hosts": (
                "GPU numbers are the committed A100 measurements in "
                "bench/results/timings.json. No host below has a GPU attached; "
                "speedups involving them are arithmetic on existing numbers."),
            "hosts": {},
            "datasets": {},
        }
        payload["hosts"][REF_LABEL] = {
            "role": "current R reference",
            "r": "4.6.0", "deseq2": "1.52.0", "apeglm": "1.34.0",
            "source": "bench/results/timings.json",
        }
        for h in hosts:
            m = h["meta"]
            payload["hosts"][h["label"]] = {
                "role": "additional R baseline",
                "host": m.get("host"), "r": m.get("r"), "deseq2": m.get("deseq2"),
                "apeglm": m.get("apeglm"), "blas": m.get("blas"),
                "measured_utc": m.get("utc"), "source": h["path"],
                "comparable_to_reference": m.get("deseq2") == "1.52.0",
            }
        for c in cases:
            d = {"r_serial_ms": {REF_LABEL: ref.get(c, {}).get("total")},
                 "r_substeps_ms": {REF_LABEL: {s: ref.get(c, {}).get(s) for s in SUBSTEPS}}}
            for h in hosts:
                row = h["fine"].get(c, {})
                d["r_serial_ms"][h["label"]] = row.get("total")
                d["r_substeps_ms"][h["label"]] = {s: row.get(s) for s in SUBSTEPS}
                d.setdefault("n", row.get("n")); d.setdefault("genes", row.get("genes"))
                d.setdefault("P", row.get("P"))
                tots = {r["workers"]: r["total"] for r in h["sweep"]
                        if r.get("case") == c and not r.get("failed")}
                if tots:
                    bw = min(tots, key=lambda w: tots[w])
                    d.setdefault("r_multicore_ms", {})[h["label"]] = {
                        "by_workers": tots, "best_ms": tots[bw], "best_workers": bw}
            crow = cu.get(c) if cu else None
            if crow:
                ms = {m: crow[m]["total"] for m in ("eager", "graph", "triton") if m in crow}
                mode = min(ms, key=ms.get)
                d["gpu_best_a100"] = {"mode": mode, "total_ms": ms[mode]}
                sp = {}
                if ref.get(c, {}).get("total"):
                    sp[f"vs_{REF_LABEL}_serial"] = round(ref[c]["total"] / ms[mode], 2)
                for h in hosts:
                    nv = h["fine"].get(c, {}).get("total")
                    if nv:
                        sp[f"vs_{h['label']}_serial"] = round(nv / ms[mode], 2)
                    mc = d.get("r_multicore_ms", {}).get(h["label"], {}).get("best_ms")
                    if mc:
                        sp[f"vs_{h['label']}_best_multicore"] = round(mc / ms[mode], 2)
                d["speedup_recomputed"] = sp
            payload["datasets"][c] = d
        jp = pathlib.Path(args.json_out)
        jp.parent.mkdir(parents=True, exist_ok=True)
        jp.write_text(json.dumps(payload, indent=2) + "\n")
        print(f"wrote {jp}")


if __name__ == "__main__":
    main()
